[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
stake = "3bUy55JLr8ra1g1GT7bn7S2KNHPxZtoyc6uf9rcYG4tm"

[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
# Token Metadata program
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
[[test.validator.clone]]
# Token Auth Rules program
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"
[[test.validator.clone]]
# Metaplex ruleSet
address = "eBJLFYPxJmMGKuFwpDWkzxZeUrad92kZRC5BJLpzyT9"

[registry]
url = "https://api.apr.dev"

[test]
upgradeable = true

[provider]
cluster = "Localnet"
wallet = "/Users/joefitter/.config/solana/id.json"
# cluster = "https://devnet.helius-rpc.com/?api-key=d8bb99b6-342b-40d8-9d9f-731827589922"
# wallet = "/Users/joefitter/.config/solana/launchpad-wallets/xlaunchpad.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
